APP_VERSION = "0.1.0"

SMA_SHORT_WINDOW = 20
SMA_LONG_WINDOW = 50
EMA_WINDOW = 20
RSI_WINDOW = 14
ATR_WINDOW = 14
VOLATILITY_WINDOW = 20

RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_BULLISH_MIN = 55
RSI_BEARISH_MAX = 45

TREND_THRESHOLD_PCT = 1.0
VOLATILE_RATIO = 1.5
BREAKOUT_RATIO = 1.2
REGIME_LOOKBACK = 20

DEFAULT_HOLDING_DAYS = 10
DEFAULT_TRANSACTION_COST_PCT = 0.1
DEFAULT_STOP_ATR_MULTIPLIER = 2.0
DEFAULT_TAKE_PROFIT_ATR_MULTIPLIER = 4.0

LOW_CONFIDENCE_TRADES = 10
MEDIUM_CONFIDENCE_TRADES = 30

SCAN_HIT_RATE_WEIGHT = 0.4
SCAN_AVERAGE_RETURN_WEIGHT = 10
SCAN_SHARPE_WEIGHT = 10
